#Docker compose file format version: may need the same maven version
version: '3.8'

services:
#aws database does not need containerising
#app (spring boot)
 backend:
  build: ./BackEnd
  restart: on-failure
  env_file: ./.env
  ports:
   - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
  environment:
   #same as application environment in spring boot
   SPRING_APPLICATION_JSON: '{
   "spring.datasource.url" : "jdbc:mysql://database-1.cavyvvu6hnkp.us-east-1.rds.amazonaws.com/database-1?characterEncoding=utf8",
   "spring.datasource.username" : "admin_jason",
   "spring.datasource.password" : "RMIT!1234",
   "spring.jpa.hibernate.ddl-auto" : "update"	
   }'
  volumes:
  # unsure
  - .m2:/root/.m2
  # keep terminal open.
  stdin_open: true
  tty: true
