version: "3.8"

services:
  build-app:
    build: ./Account
    restart: on-failure

    ports:
      - "8080:6866"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://database-1.cavyvvu6hnkp.us-east-1.rds.amazonaws.com/database-1?characterEncoding=utf8",
        "spring.datasource.username" : "admin_jason",
        "spring.datasource.password" : "Rmit1234!",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.hibernate.naming.physical-strategy" : "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl",
        "spring.mvc.format.date" : "yyyy-MM-dd"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true