version: "3.8"

services:
  build-app:
    build: ./Record
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://database-2.cavyvvu6hnkp.us-east-1.rds.amazonaws.com/db2",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "Rmit1234!",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.hibernate.naming.physical-strategy" : "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl",
        "spring.mvc.format.date" : "yyyy-MM-dd"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true