name: SEPT Pipeline

on:
  push:
    branches:
      - main
      - temp
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  #name
  run-tests:
    #vm
    runs-on: ubuntu-latest

    #step through
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup jdk 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      #      https://www.linkedin.com/pulse/run-tests-using-github-actions-springboot-project-gabriela-badila/
      - name: Build maven packages
        run: mvn -B package --file BackEnd/pom.xml

      - name: Test with maven
        run: mvn -B test --file BackEnd/pom.xml

      - name: Publish Test Report
        if: ${{ always() }}
        uses: actions/checkout@v3
        with:
            path: BackEnd/surefire-reports/*.xml
