name: SEPT Pipeline

on:
  push:
    branches:
      - main
      - temp
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  #name
  junit-tests:
    #vm
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./BackEnd

    #step through
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup jdk 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      #  https://www.linkedin.com/pulse/run-tests-using-github-actions-springboot-project-gabriela-badila/
      - name: Build maven packages
        run: mvn -B package --file pom.xml

      - name: Test with maven
        run: mvn -B test --file pom.xml

      - name: Publish Test Report
        if: ${{ always() }}
        uses: actions/checkout@v3
        with:
            path: surefire-reports/*.xml

  #name
  flutter-tests:

    #vm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ND_Telemedicine
    steps:
      #  https://github.com/marketplace/actions/flutter-action
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 18
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter --version
      - run: flutter pub get
      - run: flutter test